# Generated by Django 4.1.1 on 2022-09-29 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='formula',
            name='parent',
            field=models.ForeignKey(blank=True, default=213, on_delete=django.db.models.deletion.CASCADE, to='mainApp.formulaconspect'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulaconspect',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category'),
            preserve_default=False,
        ),
    ]
